### ISSUE TITLE
Feature request: strip line breaks

### ISSUE THREAD

**Issue by CoDEmanX** [codedread/scour#10]
`--indent=none` removes whitespace except line breaks. An additional option to also strip these last bits would be very useful for webfonts for instance.

**Comment by CoDEmanX** [comment]
> Closed #10 via #13.

Irony of fate: 10 and 13 are the hex codes for carriage return and line feed, the two line break characters involved in this matter.

Thank you very much!

**Comment by oberstet** [comment]
@CoDEmanX  pushed 0.31: https://pypi.python.org/pypi/scour/0.31
