### ISSUE TITLE
Import unittests from old repository

### ISSUE THREAD

**Issue by Ede123** [codedread/scour#15]
As discussed at [#14](14#issuecomment-157532422) it would be nice to import the unittests from the old repository (see http://bazaar.launchpad.net/~scouring/scour/trunk/files).

Some preliminary findings:
* The unittests are run by executing `testscour.py` (which makes use of `testcss.py` and the test files in the folder `unittests`)
* It should be pretty straightforward to bring them back to life. I was already able to run the script with minimal adjustments. Some tests fail to execute (possibly due to Python 3 incompatibilities), apart from most tests seem to work (and to pass).

**Comment by oberstet** [comment]
Perfect. I think porting over the unit tests will really pay off.
