### ISSUE TITLE
Executable is missing

### ISSUE THREAD

**Issue by leoheck** [codedread/scour#288]
Hi, I am on an Ubuntu 21.10 trying to find the scour script. But it is not added to the PATH and it was not on my system too.

Apt reports it was installed
```
➜ sudo apt search python3-scour        

Sorting... Done
Full-Text Search... Done
python3-scour/impish,impish 0.38.2-1 all
  SVG scrubber and optimizer (Python 3 module)
```

But there is no script
```
➜ which scour
scour not found
```

OS version just in case
```
➜ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

**Comment by JoKalliauer** [comment]
@leoheck :

Did you try
```bash
sudo apt install python3-pip scour  python3-scour
python3 -m pip install --upgrade pip
pip3 install scour
python3 -m scour.scour --help
```

I recommend to set python3 as your default python:
`sudo apt install  python-is-python3`

The python-version you are using might be interesting:
```
pip3 --version
pip --version
python3 --version
python --version
python2 --version
```

**Comment by leoheck** [comment]
I still did not know what happen. But it is working now.
Thanks for your tip. 

I was using python3. But this issue does not have anything with python.

What I was reporting is that scour script was not installed in the system. But now it is, here, `/usr/bin/scour`
I was using the Universe repository, and then scour there may not be well created. Removing this repository made it work (I believe)
