### ISSUE TITLE
Inkscape layers

### ISSUE THREAD

**Issue by moltra** [codedread/scour#289]
When using Inkscape and saving as Optimized SVG, it uses Scour to reduce the file size.   is there a way to prevent all the layers from being merged?

**Comment by JoKalliauer** [comment]
> When using Inkscape and saving as Optimized SVG, it uses Scour to reduce the file size. is there a way to prevent all the layers from being merged?

activate `--keep-editor-data` see https://github.com/scour-project/scour/wiki/Documentation#--keep-editor-data
