### ISSUE TITLE
Support both Python 2 and 3

### ISSUE THREAD

**Issue by oberstet** [codedread/scour#30]
scour should run on both Python 2 and 3. This can be done with some coding discipline

**Comment by Ede123** [comment]
Can you elaborate? Is this supposed to be an "ongoing target" or have you spotted any issues with Python 2?

Just asking because the current code seems to work fine with Python 2.7 for me and also the version I adapted for Inkscape (which is based on the unmodified code from this repository) runs well with Python 2.6.5 (which is what Inkscape bundles on Windows).

**Comment by oberstet** [comment]
Sure it works on Py 2 now, but not Py3. What I meant: we don't want to drop support for Py2, and support Py3-only, but want to support both from one code base.

**Comment by oberstet** [comment]
We should support Python 2.7 and Python 3.3+.

Python 2.6 is being phased out everywhere, and isn't supported by the Python project any longer anyway.

**Comment by Ede123** [comment]
Great then we're on the same page.... As you might have noticed I also made sure that the Unittests work both on Python 2.7 and python 3.5

Regarding Python 3. It does not work for you? I do all my development with Python 3.5 and haven't found any issues. Are you using an older version?

Regarding Python 2.6: In the long run I totally agree but for the time being we have to keep dependent projects in mind. As long as Inkscape (and you probably know that this is my main development interest) does not upgrade to at least 2.7 we should not blindly drop compatibility.

**Comment by Ede123** [comment]
@oberstet Sorry to bug you again, but you should really explain **why** Python 3 does not work for you as you just claimed again in f05d73b859094d573b8a3c7ea550d0e700bade57.

As I wrote above: Scour (the current version which is located in this repository) works just fine for me with Python 3.5, so I can not confirm this limitation!

At the very least state which version of Python you're using and maybe a copy of the error you're getting so other people can check...

**Comment by oberstet** [comment]
@Ede123 you are right: just rechecked on a Py 3.4 virtualenv .. seems to install. but do the unit tests pass? sorry for my swift replies/actions .. I am extremely short in time ..

**Comment by Ede123** [comment]
In Python 3.5 on Windows 7 the unittests work just fine.

That's my main development where I do all my coding, so I should have noticed if there were any issues.

**Comment by oberstet** [comment]
@Ede123 thanks! I've updated the readme
