### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by 4evermaat** [codedread/scour#50]
I am using inkscape 0.91 and I read in a [stackexchange article](http://graphicdesign.stackexchange.com/a/50876/63760) about the scour tool and how it can reduce file sizes of .svg files significantly and that it was already an extension in inkscape.   But I do not see it within inkscape.  

Is there a windows version of scour?
Does the windows version of inkscape come with scour and I'm not seeing it?

**Comment by Ede123** [comment]
Scour is written in Python, so it is platform independent. You have to install the [Python interpreter](https://www.python.org/) if you want to use it as a standalone program.

However what you read is correct: Inkscape for Windows ships with a bundled version of Scour. To use it you have to use "Save as" and choose "Optimized SVG" as output format.
If everything works as it's supposed to, a dialog should then appear that allows you to set Scour settings.

**Comment by oberstet** [comment]
@4evermaat `pip install scour` should do on Windows too ..

**Comment by 4evermaat** [comment]
Can you put it in the documentation that it is bundled with inkscape and how to access it?  I had no idea how to do it until you just said something.
